version: '3.9'

services:
  backend:
    container_name: app_backend
    build: .
    ports:
      - "3333:3333" # Mapeando a porta 3333 do container para a porta 3333 do host
    working_dir: /usr/src/app
    command: npm run dev
    volumes: 
      - ./backend/src:/usr/src/app/src
    depends_on:
      db:
        condition: service_healthy
    environment:
      - TZ=UTC
      - PORT=3333
      - HOST=localhost
      - LOG_LEVEL=info
      - APP_KEY=qv_Db_fOJQes7NRpBjDNPMxm4b6i2Jok
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=123456
      - DB_DATABASE=sales_management
      - JWT_SECRET=my_super_secret
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3333"]
      timeout: 10s
      retries: 5

  db:
    image: mysql:8.0.32
    container_name: db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=sales_management
    restart: 'always'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE

volumes:
  mysql_data:
